### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by itsthesteve** [angular-pakistan/ng-conf-2017#21]
Slides for "I am One with Angular, Angular is One with Me" is a github 404.

**Comment by afirdousi** [comment]
I am working on this with @johnpapa

**Comment by johnpapa** [comment]
https://www.slideshare.net/johnpapa/i-amonewithangular

**Comment by johnpapa** [comment]
https://github.com/angular-pakistan/ng-conf-2017/pull/24
