### ISSUE TITLE
Angular Form Validation Slides (Kara Erickson)

### ISSUE THREAD

**Issue by zachallen** [angular-pakistan/ng-conf-2017#4]
**Slides**: 
https://docs.google.com/presentation/d/1jn52fjrmvuXn5Jv2gP8ckETiKCW057Q63faMRfW3bkw/pub?start=false&loop=false&delayms=3000&slide=id.g128d8fde34_1_2

**Comment by afirdousi** [comment]
Thank you so much @zachallen . This has been added now.
