### ISSUE TITLE
Consider using h3/h4 for talk headings so they can be linked to

### ISSUE THREAD

**Issue by dougludlow** [angular-pakistan/ng-conf-2017#5]
Awesome resource! Thank you! One improvement: I'd love to share links to specific talks, however there's no way to create anchors to them. Please consider using h3/h4 (###/####) for the talk titles instead of code (``). I could create a pull request if you'd like.

**Comment by afirdousi** [comment]
We are using headings to divide this long list into resources from each day. Its easier if you can just share missing links here directly and ill be glad to add them over.

For example check this issue : https://github.com/angular-pakistan/ng-conf-2017/issues/4

**Comment by dougludlow** [comment]
@afirdousi, right. What I'm suggesting is to use *sub* headings for the talk titles, in addition to the headings for each day, so we can link directly to a specific talk. In github readme's, when you use any heading, it adds an id to the generated heading tag that can than be used in links (i.e. https://github.com/angular-pakistan/ng-conf-2017#day-2-summary-april-6th-2016).

I'll try adding an example in a bit when I'm not on my phone. Again, I'm more than happy to create a pull request with the changes, I just wanted to get your feedback first before doing the work.

**Comment by dougludlow** [comment]
As an example, something like this:

## Day 1 Summary (April 5th, 2016)

### 1. Keynote
[Stephen Fluin](https://twitter.com/stephenfluin), [Igor Minor](https://twitter.com/IgorMinar) and [Josh Thomas](https://twitter.com/jthoms1) - [Slides]() | [Youtube](https://www.youtube.com/watch?v=anzsE2TbCyk)

Resources shared by speakers:
- [Angular Code of Conduct](github.com/angular/code-of-conduct)
- [Angular Code of Conduct Email](conduct@angular.io)
- [Developer Survey Results](https://stackoverflow.com/insights/survey/2017#technology)
- Angular Library Spec - Link not available at this time
...
