### ISSUE TITLE
Slides Needed - Mischief Maker Lukas Ruebbelke and Roger Tipping

### ISSUE THREAD

**Issue by jasonhodges** [angular-pakistan/ng-conf-2017#6]
As the title applies. Need a link to the slides for the Mischief Maker presentation

**Comment by afirdousi** [comment]
Lukas's slide deck were a custom electron app. I have requested him to provide a slide deck for it. He assured he will send them over the weekend. This will be updated soon. I will keep you posted. 
Thanks

**Comment by afirdousi** [comment]
This is now added . Slides + the electron app.
